# Torch Bezier surfaces:

https://github.com/rafcc/pytorch-bsf?tab=readme-ov-file

`!pip install pytorch-bsf`

In [23]:
import torch

def half_sphere_point(params, c, s):
    # Ensure inputs are torch tensors
    params = torch.tensor(params, dtype=torch.float32)
    c = torch.tensor(c, dtype=torch.float32)
    s = torch.tensor(s, dtype=torch.float32)
    
    # Parameters p1 and p2
    p1, p2 = params[0], params[1]
    
    # Calculate the radius using the distance between center c and surface point s
    r = torch.sqrt(torch.sum((s - c) ** 2))
    
    # Map p1 and p2 to angles theta and phi
    theta = p1 * 2 * torch.pi  # azimuthal angle, range: [0, 2*pi]
    phi = p2 * (torch.pi / 2)  # polar angle, range: [0, pi/2] for half sphere
    
    # Spherical to Cartesian coordinates
    x = r * torch.sin(phi) * torch.cos(theta) + c[0]
    y = r * torch.sin(phi) * torch.sin(theta) + c[1]
    z = r * torch.cos(phi) + c[2]
    
    # Return the 3D point as a torch tensor
    return torch.tensor([x, y, z])

# Example usage
params = [0.5, 0.5]  # Example parameters
c = [1.0, 1.0, 1.0]  # Center of the sphere
s = [2.0, 1.0, 1.0]  # Point on the surface of the sphere

point = half_sphere_point(params, c, s)
print(point)

# Define the control points
control_points = torch.tensor([
    [[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [2.0, 0.0, 0.0]],
    [[0.0, 1.0, 0.0], [1.0, 1.0, 2.0], [2.0, 1.0, 0.0]],
    [[0.0, 2.0, 0.0], [1.0, 2.0, 0.0], [2.0, 2.0, 0.0]]
])

# Define the Bernstein basis function
def bernstein_poly(i, n, t):
    return torch.tensor(
        [torch.prod(torch.arange(1, n + 1)) / (torch.prod(torch.arange(1, i + 1)) * torch.prod(torch.arange(1, n - i + 1))) * t**i * (1 - t)**(n - i) for i in range(n + 1)]
    )

# Define the surface function
def bezier_surface(u, v, control_points):
    m, n = control_points.shape[0] - 1, control_points.shape[1] - 1
    bu = bernstein_poly(torch.arange(m + 1).reshape(-1, 1), m, u)
    bv = bernstein_poly(torch.arange(n + 1).reshape(-1, 1), n, v)
    surface = torch.einsum('im,jn,ij->mn', bu, bv, control_points)
    return surface

# Sample points on the surface
u = torch.linspace(0, 1, 10)
v = torch.linspace(0, 1, 10)
points_on_surface = bezier_surface(u[:, None], v[None, :], control_points)

print("Points on the Bézier surface:")
print(points_on_surface)

tensor([0.2929, 1.0000, 1.7071])


ValueError: only one element tensors can be converted to Python scalars

In [22]:
# Sample 100 points:
import numpy as np
np.random.seed(1)

num_samples = 10
t_parameters = np.random.rand(num_samples)
t_parameters = np.vstack([t_parameters, 1-t_parameters]).T
t_parameters

bs(t_parameters)

ts = 100 + 100 * torch.rand((4, 3))
xs = 1 - ts * ts  # values corresponding to the parameters


ts

bs = torch_bsf.fit(params=ts, values=xs, degree=4)

# Predict by the trained model
t = [
    [0.1, 0.1, 0.8],
    [0.7, 0.2, 0.1],
]
x = bs(t)
print(f"{t} -> {x}")

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/homebrew/Caskroom/miniforge/base/envs/3D/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py:72: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
/opt/homebrew/Caskroom/miniforge/base/envs/3D/lib/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py:74: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.

  | Name           | Type          | Params
-------------------------------------------------
0 | control_points | ControlPoints | 45    
-------------------------------------------------
45        Trainable params
0         Non-trainable params
45        Total params
0.000     Total estimated model params size (MB)
/opt/homebrew/Caskroom/miniforge/base/envs/3D/lib/python3.9/site-packages/pytorch_lightning/trai

[[0.1, 0.1, 0.8], [0.7, 0.2, 0.1]] -> tensor([[ 0.3162,  0.8536, -0.0343],
        [ 0.3521,  0.5171, -0.4544]], grad_fn=<AddBackward0>)


In [ ]:
import open3d as o3d
from utils.scripts.archive.scene_loading_2 import get_highlighed_o3d_locations
from utils.scripts.interest_heuristic_0    import get_o3d_pcd_from_coordinates

In [ ]:
get_o3d_pcd_from_coordinates

In [3]:
bs()

tensor([[0.9600, 0.3600],
        [0.5100, 0.9100]], grad_fn=<AddBackward0>)

# Torch variant

See:

`from utils.scripts.dev_experiments import parametrized_surfaces`

In [9]:
from utils.gradient_walk_utils import intialize_input_as_tensor, initialize_trained_encoder

trained_encoder, info_dict = initialize_trained_encoder()

sample_batch    = intialize_input_as_tensor([0,0,0,0,0,0], [0,1,0,0], info_dict)
sample_batch

{'input_pos': tensor([[-0.4517, -0.0206, -0.3463, -0.0623, -0.1044,  0.0430,  0.8922,  0.9998,
           0.9381,  0.9981,  0.9945,  0.9991, -0.8060, -0.0411, -0.6497, -0.1243,
          -0.2076,  0.0860,  0.5920,  0.9992,  0.7602,  0.9922,  0.9782,  0.9963,
          -0.9542, -0.0822, -0.9878, -0.2467, -0.4061,  0.1714, -0.2992,  0.9966,
           0.1558,  0.9691,  0.9138,  0.9852,  0.5709, -0.1639, -0.3078, -0.4782,
          -0.7422,  0.3377, -0.8210,  0.9865, -0.9514,  0.8783,  0.6702,  0.9413,
          -0.9375, -0.3233,  0.5857, -0.8399, -0.9948,  0.6357,  0.3481,  0.9463,
           0.8105,  0.5427, -0.1018,  0.7719]]),
 'input_dir': tensor([[-0.6527, -0.6119,  0.9495, -0.9117,  0.2025,  0.9814, -0.7576,  0.7909,
           0.3138, -0.4109, -0.9793,  0.1918,  0.9890, -0.9680,  0.5960,  0.7492,
          -0.3966,  0.3764,  0.1480,  0.2510, -0.8030, -0.6624,  0.9180, -0.9265,
           0.2928, -0.4860, -0.9571, -0.9925, -0.7282, -0.6975, -0.9562, -0.8740,
           0.2897, -0.1

In [ ]:
sample_batch

In [12]:
torch.autograd.Variable(sample_batch["input_pos_raw"], requires_grad=True)

tensor([[-0.4687, -0.0206, -0.3536]], requires_grad=True)

In [ ]:
intialize_input_as_tensor([0,0,0], [0,1,0,0])

In [ ]:
torch.tensor()

In [ ]:

def torch_parametric_rectangle(i, j, p, e):
    """
    i, j - parameters of the location on the rectangle [0, 1]
    p - center of the rectangle
    e - external point to the rectangle
    """  
    i = torch.tensor([float(i)], requires_grad=True)
    j = torch.tensor([float(j)], requires_grad=True)
    
    pe      = e - p 
    pe_norm = torch.norm(pe)
    orient  = torch.tensor([1, 1, (-pe[0] - pe[1]) / pe[2]])
    orient  = orient / torch.norm(orient)

In [33]:
a, b = 0, 0
# a, b = .5, .5
# a, b = 1, 0
# a, b = 0, 0
# a, b = .25, .25 #angle, distnace to center
f, l, u, z = [0.9,-0.5,0], [6,2.4,2.7], [-.3,-.5, 0.8], 0.7

for b in np.arange(10) * .1:

    new_loc_pcd = get_highlighed_o3d_locations(surface_parametric(a, b, p, c, r, surface_type, debugging=True).detach().numpy(), color=[1,0,1])[0]

    #new_loc_pcd = get_highlighed_o3d_locations(surface_parametric(a, b, p, c, r, "sphere", debugging=True).detach().numpy(), color=[1,0,1])[0]

    o3d.visualization.draw_geometries([c_center_pcd, origin_pcd, points_on_circ_pcd, new_loc_pcd]\
                                     , front=f, lookat=l, up=u, zoom=z)
    
#     break

tensor([-1.], grad_fn=<MulBackward0>) tensor([-1.], grad_fn=<MulBackward0>)
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
tensor([-1.], grad_fn=<MulBackward0>) tensor([-0.8000], grad_fn=<MulBackward0>)
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
tensor([-1.], grad_fn=<MulBackward0>) tensor([-0.6000], grad_fn=<MulBackward0>)
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
tensor([-1.], grad_fn=<MulBackward0>) tensor([-0.4000], grad_fn=<MulBackward0>)
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
tensor([-1.], grad_fn=<MulBackward0>) tensor([-0.2000], grad_fn=<MulBackward

In [ ]:
f, l, u, z = [0,0,1], [10,10,0], [0,1,0], 1.6

In [15]:
get_highlighed_o3d_locations(surface_parametric(1, 1, p, c, r).detach().numpy(), color=[1,0,1])

[PointCloud with 100 points.]

In [7]:
a, b, p, c, r

(tensor([0.1648], requires_grad=True),
 tensor([0.5897], requires_grad=True),
 tensor([10., 10., 10.]),
 tensor([0., 0., 0.]),
 10)

In [20]:
10*torch.rand(1, requires_grad=True)

tensor([3.8707], grad_fn=<MulBackward0>)

In [ ]:
torch.constant_pad_nd10*torch.rand(1, requires_grad=True)

In [16]:
surface_type="circle" 
surface_type="sphere" 
surface_type="square" 

surface_parametric(0.5,0.5, p, c, r, "square"), surface_parametric(0,0, p, c, r, "circle")\
, surface_parametric(1.25, .25, p, c, r, "sphere")

(tensor([10., 10., 10.], grad_fn=<AddBackward0>),
 tensor([10., 10., 10.], grad_fn=<AddBackward0>),
 tensor([ 5.3535e-07, -1.2247e+01, -1.2247e+01]))

In [23]:
circle_parametric(0,0,p,c,r,"circle"), circle_parametric(0,0,p,c,r,"square")

(tensor([10., 10., 10.], grad_fn=<AddBackward0>),
 tensor([-1.1536, 12.9886, 18.1650], grad_fn=<AddBackward0>))

In [4]:
torch.rand(1, requires_grad=True)

tensor([0.5062], requires_grad=True)

In [18]:
torch.tensor([float(1)], requires_grad=True)

tensor([1.], requires_grad=True)

In [6]:
torch.tensor(torch.rand(1, requires_grad=True), requires_grad=True)

tensor([0.6783], requires_grad=True)

In [ ]:
origin = 

# Working torch variant:

In [11]:
import torch
import numpy as np

import open3d as o3d
import seaborn as sns


from utils.scripts.archive.scene_loading_2 import get_highlighed_o3d_locations
from utils.scripts.interest_heuristic_0    import get_o3d_pcd_from_coordinates


    
    

def surface_parametric(a, b, p, c, r, surface_type="circle", lL=None, debugging=False):
    
    a = torch.tensor([float(a)], requires_grad=True)
    b = torch.tensor([float(b)], requires_grad=True)
    
    # Calculate the vector pc
    pc      = c - p
    pc_norm = torch.norm(pc)
    orient  = torch.tensor([1,1, (- pc[0] - pc[1]) / pc[2]])
    orient  = orient / torch.norm(orient)

    # Normalize pc to get the direction
    pc_normalized = pc / pc_norm

    # Find a vector perpendicular to pc
    v_perpendicular = torch.cross(pc_normalized, orient)

    # Normalize v_perpendicular
    v_perpendicular_normalized = v_perpendicular / torch.norm(v_perpendicular)
    
    if surface_type =="circle":
        # Calculate angle theta
        theta = 2 * np.pi * a
        # Calculate the point on the circle
        circle_point = p + r * (torch.cos(theta) * orient + torch.sin(theta) * v_perpendicular_normalized)
        # Interpolate between p and the circle_point using parameter b
        final_point = (1 - b) * p + b * circle_point
    if surface_type == "square":
        # Calculate the point on the circle
        if lL is None:
            lL = (r, r)
        l, L = lL
        a = l * (a - .5) * 2
        b = L * (b -.5) * 2 
        if debugging:
            print(a, b)
        square_point = p + r * (a * orient + (b) * v_perpendicular_normalized)
        final_point  = square_point
        
    if surface_type == "sphere":  
        r     = pc_norm
        theta = a * torch.pi     #between 0 and pi
        phi   = b * 2 * torch.pi #between 0 and 2*pi

        x = c[0] + r * torch.sin(theta) * torch.cos(phi)
        y = c[1] + r * torch.sin(theta) * torch.sin(phi)
        z = c[2] + r * torch.cos(theta)

        final_point = c + torch.tensor([r * torch.sin(theta) * torch.cos(phi),0,0])
        final_point = final_point + torch.tensor([0, r * torch.sin(theta) * torch.sin(phi),0])
        final_point = final_point + torch.tensor([0, 0, r * torch.cos(theta)])
        #pass
    
    

    return final_point




# Example usage
p = torch.tensor([10, 10, 10], dtype=torch.float, requires_grad=False)  # Center point
c = torch.tensor([0, 0, 0], dtype=torch.float, requires_grad=False)  # Point on the circle
r = 10  # Radius

# Generate random values for a and b
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

# orient = torch.tensor([0, 1, 0], dtype=torch.float, requires_grad=False)

# Calculate the point on the circle using parameters a and b
# point_on_circle = surface_parametric(a, b, p, c, r)

surface_type="circle" 
surface_type="sphere" 
# surface_type="square" 
n_points = 1000
# points_on_circle = torch.tensor([circle_parametric(np.random.rand(), np.random.rand(), p, c, r) for i in range(n_points)])
# points_on_circle = [surface_parametric(torch.rand(1, requires_grad=True)\
#                                       , torch.rand(1, requires_grad=True)\
#                                       , p, c, r, surface_type) for i in range(n_points)]

# points_on_circle = [surface_parametric(0\
#                                       , torch.rand(1, requires_grad=True)\
#                                       , p, c, r, surface_type) for i in range(n_points)]

points_on_circle = [surface_parametric(torch.rand(1, requires_grad=True)*.5\
                                      , torch.rand(1, requires_grad=True)\
                                      , p, c, r, surface_type) for i in range(n_points)]

points_on_circle = torch.vstack(points_on_circle).detach().numpy()

# print("Point on the circle:", point_on_circle)

points_on_circ_pcd = get_o3d_pcd_from_coordinates(points_on_circle, [0,1,0])


# circ_pcd     = get_o3d_pcd_from_coordinates(circle_points, [0,1,0]) #green
c_center_pcd = get_highlighed_o3d_locations(p, color=[1,0,0])[0] #red
origin_pcd   = get_highlighed_o3d_locations(c, color=[0,0,1])[0] # blue


# a, b = 1, 1 #angle, distnace to center
# a, b = 0.2, 1
a, b = .5, .5
# a, b = 1, 0
# a, b = 0, 0
# a, b = .25, .25 #angle, distnace to center

new_loc_pcd = get_highlighed_o3d_locations(surface_parametric(a, b, p, c, r, surface_type, debugging=True).detach().numpy(), color=[1,0,1])[0]

new_loc_pcd = get_highlighed_o3d_locations(surface_parametric(a, b, p, c, r, "sphere", debugging=True).detach().numpy(), color=[1,0,1])[0]

# o3d.visualization.draw_geometries([c_center_pcd, origin_pcd, points_on_circ_pcd, new_loc_pcd])

In [14]:
c, p

(tensor([0., 0., 0.]), tensor([10., 10., 10.]))

In [19]:
torch.max(p, torch.tensor([1.,2.,11.], requires_grad=True))

tensor([10., 10., 11.], grad_fn=<MaximumBackward0>)

In [26]:
torch.vstack([p, c])

tensor([[10., 10., 10.],
        [ 0.,  0.,  0.]])

In [14]:
f, l, u, z = [0,0,1], [10,10,0], [0,1,0], 1.6

# Circle

In [19]:
st = "circle"

points_on_circle = torch.vstack([surface_parametric(
                    np.random.rand(1)\
                  , np.random.rand(1)\
                  , p, c, r, st) for i in range(1000)]
).detach().numpy()
points_on_circ_pcd = get_o3d_pcd_from_coordinates(points_on_circle, [0,1,0])

a, b = .25, .75
new_loc_pcd = get_highlighed_o3d_locations(surface_parametric(a, b, p, c, r, st).detach().numpy(), color=[1,0,1])[0]

o3d.visualization.draw_geometries([c_center_pcd, origin_pcd, points_on_circ_pcd, new_loc_pcd], front=f, lookat=l, up=u, zoom=z)

[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


# Rectangle

In [16]:
np.random.seed(1)

lL = (1, 2)

st = "square"

points_on_circle = torch.vstack([surface_parametric(
                    np.random.rand(1)\
                  , np.random.rand(1)\
                  , p, c, r, st, lL, False) for i in range(1000)]
).detach().numpy()
points_on_circ_pcd = get_o3d_pcd_from_coordinates(points_on_circle, [0,1,0])

a, b = .25, .75
new_loc_pcd = get_highlighed_o3d_locations(surface_parametric(a, b, p, c, r, st, lL, True).detach().numpy(), color=[1,0,1])[0]

o3d.visualization.draw_geometries([c_center_pcd, origin_pcd, points_on_circ_pcd, new_loc_pcd], front=f, lookat=l, up=u, zoom=z)

tensor([-0.5000], grad_fn=<MulBackward0>) tensor([1.], grad_fn=<MulBackward0>)
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


# Full Sphere

In [17]:
st = "sphere"
points_on_circle = np.vstack([surface_parametric(torch.rand(1, requires_grad=True)\
                                      , torch.rand(1, requires_grad=True)\
                                      , p, c, r, st) for i in range(n_points)]
)
points_on_circ_pcd = get_o3d_pcd_from_coordinates(points_on_circle, [0,1,0])

a, b = .25, .5
new_loc_pcd = get_highlighed_o3d_locations(surface_parametric(a, b, p, c, r, st).detach().numpy(), color=[1,0,1])[0]

o3d.visualization.draw_geometries([c_center_pcd, origin_pcd, points_on_circ_pcd, new_loc_pcd], front=f, lookat=l, up=u, zoom=z)

[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


# Half a Sphere

In [18]:
st = "sphere"
points_on_circle = np.vstack([surface_parametric(torch.rand(1, requires_grad=True)*.5\
                                      , torch.rand(1, requires_grad=True)\
                                      , p, c, r, st) for i in range(n_points)]
)
points_on_circ_pcd = get_o3d_pcd_from_coordinates(points_on_circle, [0,1,0])

a, b = .25, .5
new_loc_pcd = get_highlighed_o3d_locations(surface_parametric(a, b, p, c, r, st).detach().numpy(), color=[1,0,1])[0]

o3d.visualization.draw_geometries([c_center_pcd, origin_pcd, points_on_circ_pcd, new_loc_pcd], front=f, lookat=l, up=u, zoom=z)

[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


parametrized surfaces:

# Numpy variant

In [1]:
import open3d as o3d
import seaborn as sns


from utils.scripts.archive.scene_loading_2 import get_highlighed_o3d_locations
from utils.scripts.interest_heuristic_0    import get_o3d_pcd_from_coordinates

import numpy as np
x, y, z    = 12,12,12
cx, cy, cz = 0,0,0
r = 4

# Define the points p and c
p = np.array([x, y, z])  # Center point
c = np.array([cx, cy, cz])  # Point on the circle

# Calculate the vector pc
pc = c - p

# Normalize pc to get the direction
pc_normalized = pc / np.linalg.norm(pc)

# Find a vector perpendicular to pc
# We can use the cross product with any vector that is not parallel to pc
# For simplicity, we'll choose the x-axis vector [1, 0, 0]
v_perpendicular = np.cross(pc_normalized, [1, 0, 0])

# Normalize v_perpendicular
v_perpendicular_normalized = v_perpendicular / np.linalg.norm(v_perpendicular)

# Now we have two perpendicular vectors: pc_normalized and v_perpendicular_normalized
# We can use them to parametrize the circle
# The parametric equation of a circle in 3D is:
# x = cx + r * cos(t)
# y = cy + r * sin(t)
# z = cz

# Generate t values from 0 to 2*pi
t_values = np.linspace(0, 2 * np.pi, 100)

# Parametric equations of the circle
circle_points = c + r * (np.cos(t_values)[:, np.newaxis] * pc_normalized +
                         np.sin(t_values)[:, np.newaxis] * v_perpendicular_normalized)

circ_pcd     = get_o3d_pcd_from_coordinates(circle_points, [0,1,0]) #green
c_center_pcd = get_highlighed_o3d_locations(p, color=[1,0,0])[0] #red
origin_pcd   = get_highlighed_o3d_locations(c, color=[0,0,1])[0] # blue


o3d.visualization.draw_geometries([c_center_pcd, origin_pcd, circ_pcd])

[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


In [28]:
import numpy as np

def circle_parametric(a, b, p, c, r, orientation=[1,0,0]):
    # Calculate the vector pc
    pc = c - p

    # Normalize pc to get the direction
    pc_normalized = pc / np.linalg.norm(pc)

    # Find a vector perpendicular to pc
    # We can use the cross product with any vector that is not parallel to pc
    # For simplicity, we'll choose the x-axis vector [1, 0, 0]
    v_perpendicular = np.cross(pc_normalized, [1, 0, 0])

    # Normalize v_perpendicular
    v_perpendicular_normalized = v_perpendicular / np.linalg.norm(v_perpendicular)

    # Calculate angle theta
    theta = 2 * np.pi * a

    # Calculate the point on the circle
    circle_point = c + r * (np.cos(theta) * pc_normalized + np.sin(theta) * v_perpendicular_normalized)

    # Interpolate between p and the circle_point using parameter b
    final_point = (1 - b) * p + b * circle_point

    return final_point

# Example usage
p = np.array([0, 0, 0])  # Center point
c = np.array([1, 1, 1])  # Point on the circle
r = 4  # Radius

# Generate random values for a and b
a = np.random.rand()
b = np.random.rand()

# Calculate the point on the circle using parameters a and b
point_on_circle = circle_parametric(a, b, p, c, r)

n_points = 1000
points_on_circle = np.array([circle_parametric(np.random.rand(), np.random.rand(), p, c, r) for i in range(n_points)])

print("Point on the circle:", point_on_circle)

points_on_circ_pcd = get_o3d_pcd_from_coordinates(points_on_circle, [1,0,1])


o3d.visualization.draw_geometries([c_center_pcd, origin_pcd, circ_pcd, points_on_circ_pcd])

Point on the circle: [ 0.05225199  2.01768091 -1.91317693]
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


In [22]:
a, b*2

(tensor([0.9432], requires_grad=True),
 tensor([0.8846], grad_fn=<MulBackward0>))

In [24]:
torch.tensor([a,b*2])

tensor([0.9432, 0.8846])

In [20]:
torch.norm(p-c), torch.pi

(tensor(17.3205), 3.141592653589793)

In [34]:
torch.dot(p-c, p-c)

tensor(3.)

In [44]:
torch.tensor([1,1, (- (p-c)[0] - (p-c)[1]) / (p-c)[2] ])

tensor([ 1.,  1., -2.])

In [41]:
torch.hstack([[1],[1], (p-c)[0], (p-c)[1], (p-c)[2]])

TypeError: expected Tensor as element 0 in argument 0, but got list

In [9]:
[circle_parametric(torch.rand(1, requires_grad=True), torch.rand(1, requires_grad=True), p, c, r, orient) for i in range(n_points)]

tensor([0.3598, 0.0456, 0.2027], grad_fn=<AddBackward0>)

In [8]:
torch.tensor([circle_parametric(torch.rand(1, requires_grad=True),torch.rand(1, requires_grad=True), p, c, r, orient) for i in range(100)])

ValueError: only one element tensors can be converted to Python scalars

In [25]:
import numpy as np

def sphere(a, b, p, c):
    # Calculate the vector pc
    pc = c - p
    
    # Calculate the radius of the sphere
    r = np.linalg.norm(pc)
    
    # Calculate theta and phi based on a and b
    theta = np.arccos(2 * b - 1)  # theta varies from 0 to pi
    phi = 2 * np.pi * a  # phi varies from 0 to 2*pi
    
    # Calculate the point on the surface of the sphere
    x = c[0] + r * np.sin(theta) * np.cos(phi)
    y = c[1] + r * np.sin(theta) * np.sin(phi)
    z = c[2] + r * np.cos(theta)
    
    return np.array([x, y, z])

# Example usage
p = np.array([1, 2, 3])  # Arbitrary point in 3D space
c = np.array([0, 0, 0])  # Center point of the sphere

# Generate points on the sphere for a = 0, b = 0 and a = 1, b = 1
point_on_sphere_1 = sphere(0, 0, p, c)
point_on_sphere_2 = sphere(1, 1, p, c)

print("Point on the sphere for a = 0, b = 0:", point_on_sphere_1)
print("Point on the sphere for a = 1, b = 1:", point_on_sphere_2)


Point on the sphere for a = 0, b = 0: [ 4.58220874e-16  0.00000000e+00 -3.74165739e+00]
Point on the sphere for a = 1, b = 1: [0.         0.         3.74165739]
